### ISSUE TITLE
[CRASH] Windows / 6.0.3 crash on start - dht_get_peers_reply_alert_alert_type_get

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-desktop#378]
```
FrostWire version 6.0.3 build 1
Java version 1.8.0_11 from Oracle Corporation
Windows 8 v. 6.2 on x86
Free/total memory: 8978848/16318464

FATAL ERROR!

java.lang.UnsatisfiedLinkError: com.frostwire.jlibtorrent.swig.libtorrent_jni.dht_get_peers_reply_alert_alert_type_get()I
        at com.frostwire.jlibtorrent.swig.libtorrent_jni.dht_get_peers_reply_alert_alert_type_get(Native Method)
        at com.frostwire.jlibtorrent.swig.dht_get_peers_reply_alert.<clinit>(Unknown Source)
        at com.frostwire.jlibtorrent.alerts.AlertType.<clinit>(Unknown Source)
        at com.frostwire.bittorrent.BTEngine.<clinit>(Unknown Source)
        at com.limegroup.gnutella.gui.Initializer.startBittorrentCore(Unknown Source)
        at com.limegroup.gnutella.gui.Initializer.initialize(Unknown Source)
        at com.limegroup.gnutella.gui.GUILoader.load(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.limegroup.gnutella.gui.Main.main(Unknown Source)
```

@aldenml think the uninstaller is not replacing the old dll?

**Comment by gubatron** [comment]
@aldenml probably unrelated but dht_get_peer seems to have issues on some windows instances too.

**Comment by aldenml** [comment]
Yes, not related, but strange.
