### ISSUE TITLE
BTDownload -> PiecesTracker NPE

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-desktop#425]
```
INFO: Error calling alert listener
java.lang.NullPointerException
	at com.frostwire.jlibtorrent.PiecesTracker.<init>(PiecesTracker.java:19)
	at com.frostwire.bittorrent.BTDownload.<init>(BTDownload.java:77)
	at com.frostwire.bittorrent.BTEngine$InnerListener.alert(BTEngine.java:785)
	at com.frostwire.jlibtorrent.Session.fireAlert(Session.java:863)
	at com.frostwire.jlibtorrent.Session.access$400(Session.java:31)
	at com.frostwire.jlibtorrent.Session$1.run(Session.java:938)
	at java.lang.Thread.run(Thread.java:745)
```

I'm seeing this a lot when performing searches, I don't want to apply a try/catch type of patch to silence it as I know you were working with the PiecesTracker.

**Comment by aldenml** [comment]
Fixed with https://github.com/frostwire/frostwire-common/commit/197b3fe00e28dd7ccdfd8fe88dc92e7a3544504a

**Comment by gubatron** [comment]
![thanks](https://cloud.githubusercontent.com/assets/163977/6305309/3e34c760-b8f8-11e4-947f-98fa4f9107e3.gif)
