### ISSUE TITLE
6.0.8 build 1: Unsatisfied Link Error [BTEngine.start()]

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-desktop#453]
Also some users report that FrostWire is crashing when it's "Checking...", might be related to this crash.

```
FrostWire version 6.0.8 build 1
Java version 1.8.0_40 from Oracle Corporation
Windows 7 v. 6.1 on x86
Free/total memory: 9442784/16318464

FATAL ERROR!

java.lang.UnsatisfiedLinkError: com.frostwire.jlibtorrent.swig.libtorrent_jni.new_session__SWIG_4(JLcom/frostwire/jlibtorrent/swig/fingerprint;JLcom/frostwire/jlibtorrent/swig/int_int_pair;Ljava/lang/String;II)J
        at com.frostwire.jlibtorrent.swig.libtorrent_jni.new_session__SWIG_4(Native Method)
        at com.frostwire.jlibtorrent.swig.session.<init>(Unknown Source)
        at com.frostwire.jlibtorrent.Session.<init>(Unknown Source)
        at com.frostwire.jlibtorrent.Session.<init>(Unknown Source)
        at com.frostwire.jlibtorrent.Session.<init>(Unknown Source)
        at com.frostwire.bittorrent.BTEngine.start(Unknown Source)
        at com.frostwire.bittorrent.BTEngine.reloadBTContext(Unknown Source)
        at com.limegroup.gnutella.gui.Initializer.startBittorrentCore(Unknown Source)
        at com.limegroup.gnutella.gui.Initializer.initialize(Unknown Source)
        at com.limegroup.gnutella.gui.GUILoader.load(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.limegroup.gnutella.gui.Main.main(Unknown Source)
```

**Comment by aldenml** [comment]
This is ver very early in the startup. One possibility for this situation is: somehow the dll got infected by a virus and the anti-virus protection removed the threat. Then the library is missing.

@muckachina if we can request that the user perform a manual verification of the existence of this file (jlibtorrent.dll) in the installation folder, that could help.

**Comment by muckachina** [comment]
@gubatron where did you get this report so I can check with the user Alden' suggestion?

**Comment by gubatron** [comment]
on our email, gets sent to doctor.frostwire.com when FrostWire crashes.

I suppose @aldenml you checked the dll for the symbol and it is there.

**Comment by muckachina** [comment]
I cannot find that log-message guys, I only get mails from contact and support. 

If you can forward to me that mail from doctor.frostwire.com I can try to contact the user.

**Comment by gubatron** [comment]
the message is anonymous @muckachina .

In anycase, it seems like this is not a severe issue, we got this error 3 times on the 27th of april, and nothing new since. It might be like @aldenml 

The emails look like this on my inbox:
![screen shot 2015-04-29 at 5 04 40 pm](https://cloud.githubusercontent.com/assets/163977/7401432/f9d7b152-ee91-11e4-892c-7aa89c8517d3.png)

I've doubled checked and the email is getting sent to your account, might want to check your spam folder, from emails coming from `noreply@frostwire.com`

**Comment by muckachina** [comment]
mmm thanks for letting me know, it was going there
