### ISSUE TITLE
[6.1.4 build 2] Soundcloud search: 401 Unauthorized

### ISSUE THREAD

**Issue by Beanow** [frostwire/frostwire-desktop#465]
Searching for a Soundcloud url results in a 401 on the console.

It's triggered by the request at [BTDownloadMediator.java:854](https://github.com/frostwire/frostwire-desktop/blob/master/src/com/frostwire/gui/bittorrent/BTDownloadMediator.java#L854)

```
resolve: <..the url..>
java.io.IOException: Server returned HTTP response code: 401 for URL: <..the url..>
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at com.frostwire.util.JdkHttpClient.get(Unknown Source)
	at com.frostwire.util.JdkHttpClient.get(Unknown Source)
	at com.frostwire.util.JdkHttpClient.get(Unknown Source)
	at com.frostwire.util.JdkHttpClient.get(Unknown Source)
	at com.frostwire.util.JdkHttpClient.get(Unknown Source)
	at com.frostwire.gui.bittorrent.BTDownloadMediator.downloadSoundcloudFromTrackUrlOrSearchResult(Unknown Source)
	at com.limegroup.gnutella.gui.GUIMediator.openSoundcloudTrackUrl(Unknown Source)
	at com.limegroup.gnutella.gui.actions.FileMenuActions.openMagnetOrTorrent(Unknown Source)
	at com.limegroup.gnutella.gui.ApplicationHeader$SearchListener.actionPerformed(Unknown Source)
	at javax.swing.JTextField.fireActionPerformed(JTextField.java:508)
	at com.frostwire.gui.searchfield.SearchField.fireActionPerformed(Unknown Source)
	at javax.swing.JTextField.postActionEvent(JTextField.java:721)
	at com.frostwire.gui.searchfield.JXSearchField.postActionEvent(Unknown Source)
	at javax.swing.JTextField$NotifyAction.actionPerformed(JTextField.java:836)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at com.frostwire.gui.searchfield.SearchField.processKeyEvent(Unknown Source)
	at com.limegroup.gnutella.gui.ApplicationHeader$1.processKeyEvent(Unknown Source)
	at java.awt.Component.processEvent(Component.java:6312)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4762)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by gubatron** [comment]
This was preciselt the fix made on 6.1.5, please download the latest version from (frostwire.com)[http://frostwire.com/downloads]

**Comment by Beanow** [comment]
I'm running it on linux, for which the download has not yet been released.

**Comment by gubatron** [comment]
sorry about that, I'll be working personally today on the Linux build.
In the meantime you can always run it from source in  linux.
